maven-build: 
  image: maven:3.8.8-eclipse-temurin-11-alpine
  stage: build
  cache:
    key: maven-cache
    paths: [.repository/]
  before_script:
   - cp -r ./devops/config/* ./source/${NAME_FOLDER}/src/main/resources/
   - cd source
   - sed -i "s/{DB_DATABASE}/${DB_DATABASE}/g" ./${NAME_FOLDER}/src/main/resources/application-dev.properties
   - sed -i "s/{HOST}/${HOST}/g" ./${NAME_FOLDER}/src/main/resources/application-dev.properties
   - sed -i "s/{DB_USERNAME}/${DB_USERNAME}/g" ./${NAME_FOLDER}/src/main/resources/application-dev.properties
   - sed -i "s/{DB_KEY}/${DB_KEY}/g" ./${NAME_FOLDER}/src/main/resources/application-dev.properties
  script: 
   - sed -i "s/{APP_DEV_PORT}/${APP_DEV_PORT}/g" ./${NAME_FOLDER}/src/main/resources/application-dev.properties
   - cd ${NAME_FOLDER}
   - mvn clean package -Dmaven.test.skip
   
   - ls ./source/${NAME_FOLDER}/target
  artifacts:
    paths:
      - ./source/${NAME_FOLDER}/target/*.jar
  only:
    - dev