maven-build: 
  image: maven:3.8.8-eclipse-temurin-11-alpine
  stage: build
  cache:
    key: maven-cache
    paths: [.repository/]
  before_script:
   - ls ./devops/config 
   - ls ./source/src/main/resources
   - cp -r ./devops/config/* ./source/src/main/resources/
   - cd source
   - ls -a
   - sed -i "s/{DB_DATABASE}/${DB_DATABASE}/g" ./src/main/resources/application-dev.properties
   - sed -i "s/{HOST}/${HOST}/g" ./src/main/resources/application-dev.properties
   - sed -i "s/{DB_USERNAME}/${DB_USERNAME}/g" ./src/main/resources/application-dev.properties
   - cat ./src/main/resources/application-dev.properties
  #  - sed -i "s/{DB_PASS}/${DB_PASS}/g" ./src/main/resources/application-dev.properties
   - cat ./src/main/resources/application-dev.properties
  script: 
   - sed -i "s/{APP_DEV_PORT}/${APP_DEV_PORT}/g" ./src/main/resources/application-dev.properties
   - cat ./src/main/resources/application-dev.properties
   - mvn clean package -Dmaven.test.skip
  artifacts:
    paths:
      - source/target/*.jar
  only:
    - dev