build-image:
  stage: build-image
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  # before_script:

  #   - sed -i "s/{PORT}/${APP_DEV_PORT}/g" appServer.js
  #   - cd devops 
  #   - cp -r ./source/build ./devops/
  script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS
    - docker build --cache-from ${DOCKER_CACHE_IMAGE}
        --tag ${DOCKER_CACHE_IMAGE}
        --tag ${DOCKER_REPO}:${CI_COMMIT_SHA:0:8} .
    - docker image push ${DOCKER_REPO}:${CI_COMMIT_SHA:0:8}
    - docker image push ${DOCKER_CACHE_IMAGE}
  
  only:
    - dev