deploy:
  stage: deploy
  before_script:
    - chmod 400 $MASTER_SSH_KEY
  script:
    
    - ssh -o StrictHostKeyChecking=no -i $MASTER_SSH_KEY root@phatluu.website "docker rm -f ${CI_PROJECT_NAME} || true"
    - ssh -o StrictHostKeyChecking=no -i $MASTER_SSH_KEY root@phatluu.website "docker rmi \$(docker images -q ${DOCKER_REPO}) || true"
    # deploy
    - ssh -o StrictHostKeyChecking=no -i $MASTER_SSH_KEY root@phatluu.website "docker container run -d --name ${CI_PROJECT_NAME} -p ${APP_DEV_PORT}:${APP_DEV_PORT} --env SPRING_PROFILES_ACTIVE=dev $IMAGE_NAME:${CI_COMMIT_SHA:0:8}"
  only:
    - dev