deploy:
  stage: deploy
  before_script:
    - chmod 400 $MASTER_SSH_KEY
  script:
    - ssh -o StrictHostKeyChecking=no -i $MASTER_SSH_KEY root@14.225.210.81 "docker stop ${CI_PROJECT_NAME} || true"
    - ssh -o StrictHostKeyChecking=no -i $MASTER_SSH_KEY root@14.225.210.81 "docker rm -f ${CI_PROJECT_NAME} || true"
    - ssh -o StrictHostKeyChecking=no -i $MASTER_SSH_KEY root@14.225.210.81 "docker rmi \$(docker images -q ${DOCKER_REPO}) || true"
    # deploy
    - ssh -o StrictHostKeyChecking=no -i $MASTER_SSH_KEY root@14.225.210.81 "docker container run -d --name ${CI_PROJECT_NAME} --expose ${APP_DEV_PORT} --env "VIRTUAL_HOST=$DOMAIN" --env "LETSENCRYPT_HOST=$DOMAIN" $IMAGE_NAME:${CI_COMMIT_SHA:0:8}"
  only:
    - dev